#!/usr/bin/env python
# coding: utf-8

# In[1]:


pip install selenium 


# In[2]:


pip install pyautogui


# In[1]:


from selenium import webdriver
from selenium.webdriver.chrome.service import Service 
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys 
import pyautogui as pag
import time
import os


# In[5]:


class Browser:
    browser, service = None, None 
    
    #Initialise the webdriver with the path to chromedriver.exe 
    def __init__(self,driver: str):
        self.service = webdriver.chrome.service.Service(driver)
        self.browser = webdriver.Chrome(service = self.service)
    def open_page(self, url: str):
        self.browser.get(url)
    def close_browser(self):
        self.browser.close()
    def add_input(self,by:By,value:str,text:str):
        field = self.browser.find_element(by=by,value=value)
        field.send_keys(text)
        time.sleep(1)
    def click_button(self, by:By, value: str):
        button = self.browser.find_element(by=by,value=value)
        button.click()
        time.sleep(1)
    def login_linkedin(self,username:str,password:str):
        self.add_input(by=By.ID, value='username', text=username)
        self.add_input(by=By.ID, value='password',text=password)
        self.click_button(by=By.CSS_SELECTOR, value='button.btn__primary--large.from__button--floating')
    def create_post(self,content:str):
        self.click_button(by=By.CLASS_NAME, value='share-box-feed-entry__top-bar')
        self.add_input(by=By.CSS_SELECTOR, value='.ql-editor',text=content)
        self.click_button(by=By.CSS_SELECTOR, value='.share-actions__primary-action.artdeco-button--primary')
    def apply_to_job(self,jobtitle:str,):
        self.add_input(by=By.CLASS_NAME, value='jobs-search-box__text-input',text=jobtitle)
        self.browser.find_element(By.CLASS_NAME, 'jobs-search-box__text-input').send_keys(Keys.ENTER)
        time.sleep(3)
   
        

    
if __name__ == '__main__':
        browser = Browser('C:\\Web Drivers\\chromedriver.exe')
        
        browser.open_page('https://www.linkedin.com/login')
        time.sleep(3)
        
        browser.login_linkedin(username= 'ishitawork67@gmail.com',password = 'Ishidi@456')
        time.sleep(3)
        
        browser.create_post(content='This is an autogenerated post of the bot I am creating using selenium library in python!')
        time.sleep(3)
        
        browser.open_page('https://www.linkedin.com/jobs/')
        time.sleep(3)
        
        browser.apply_to_job(jobtitle='Project management Internship')
        time.sleep(3)
        
        browser.open_page('https://www.linkedin.com/mynetwork/')
        time.sleep(3)
   
        browser.open_page('https://www.linkedin.com/feed/')


# In[ ]:





# In[ ]:





# In[4]:





# In[ ]:





# In[ ]:




